--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/PersonaSkin-PMMP
build-by-default: true
branches:
  - main
projects:
  PersonaSkin:
    icon: "icon.png"
    libs:
      - src: PresentKim/png-converter/png-converter
        version: ^1.0.2
...
